### PR TITLE
ensure HTTP requests use proxy env vars

### PR DESCRIPTION
**Pull request by ncsc-ie-devs**
#### **Description**
This merge request resolves [Issue 596](#596)  by ensuring that all HTTP and HTTPS traffic uses the proxy configuration specified in the environment variables (`HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY`).

#### **Changes Made**
- Updated all instances of `http.Transport` to include the `Proxy` field:
  ```go
  Proxy: http.ProxyFromEnvironment
  ```
- Ensured compatibility with existing `TLSClientConfig` settings, preserving secure connections.

#### **Motivation**
The issue described in [Issue 596](#596) identified a shortfall where proxy settings were ignored, causing failures in proxied environments. This fix ensures compliance with Go's standard proxy behavior and improves usability for users in corporate or secured networks.

#### **Verification**
1. **Environment Setup**:
   - Configured proxy settings using `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY`.
   - Verified traffic routing through the proxy and bypassing for domains listed in `NO_PROXY`.

2. **Test Cases**:
   - Successful request routing through a proxy server.
   - Proper bypassing of proxy for `NO_PROXY`-listed domains.

#### **Impact**
- Resolves connection issues for users in proxied environments.
- Aligns the application with standard Go behavior for `net/http` proxy handling.

#### **Closes**
Closes [Issue 596](#596).

### CODE REVIEW

**Review by s-l-teichmann — DISMISSED** [review]
LGTM

**Comment by koplas** [comment]
@ncsc-ie-devs Can you run `go fmt ./...` on your code?

**Comment by ncsc-ie-devs** [comment]
> @ncsc-ie-devs Can you run `go fmt ./...` on your code?

That should be done now - sorry about the delay.

**Comment by koplas** [comment]
LGTM & works

**Comment by bernhardreiter** [comment]
@koplas should we additionally add a remark in a general place in the documenation?

**Review by s-l-teichmann — APPROVED** [review]
LGTM

**Pull request merged**
